candle_pattern_names = {
    "CDL2CROWS": "Two Crows",
    "CDL3BLACKCROWS": ("Three Black Crows", 3),
    "CDL3INSIDE": ("Three Inside Up/Down", 3),
    "CDL3LINESTRIKE": "Three-Line Strike",
    "CDL3OUTSIDE": ("Three Outside Up/Down", 3),
    "CDL3STARSINSOUTH": "Three Stars In The South",
    "CDL3WHITESOLDIERS": ("Three White Soldiers", 3),
    "CDLABANDONEDBABY": ("Abandoned Baby", 3),
    "CDLADVANCEBLOCK": ("Advance Block", 2),
    "CDLBELTHOLD": ("Belt-hold", 1),
    "CDLBREAKAWAY": "Breakaway",
    "CDLCLOSINGMARUBOZU": "Closing Marubozu",
    "CDLCONCEALBABYSWALL": "Concealing Baby Swallow",
    "CDLCOUNTERATTACK": "Counterattack",
    "CDLDARKCLOUDCOVER": "Dark Cloud Cover",
    "CDLDOJI": "Doji",
    "CDLDOJISTAR": ("Doji Star", 2),
    "CDLDRAGONFLYDOJI": ("Dragonfly Doji", 2),
    "CDLENGULFING": ("Engulfing Pattern", 2),
    "CDLEVENINGDOJISTAR": ("Evening Doji Star", 3),
    "CDLEVENINGSTAR": ("Evening Star", 3),
    "CDLGAPSIDESIDEWHITE": "Up/Down-gap side-by-side white lines",
    "CDLGRAVESTONEDOJI": ("Gravestone Doji", 2),
    "CDLHAMMER": ("Hammer", 1),
    "CDLHANGINGMAN": ("Hanging Man", 1),
    "CDLHARAMI": ("Harami Pattern", 1),
    "CDLHARAMICROSS": ("Harami Cross Pattern", 1),
    "CDLHIGHWAVE": "High-Wave Candle",
    "CDLHIKKAKE": "Hikkake Pattern",
    "CDLHIKKAKEMOD": "Modified Hikkake Pattern",
    "CDLHOMINGPIGEON": "Homing Pigeon",
    "CDLIDENTICAL3CROWS": "Identical Three Crows",
    "CDLINNECK": "In-Neck Pattern",
    "CDLINVERTEDHAMMER": ("Inverted Hammer", 1),
    "CDLKICKING": "Kicking",
    "CDLKICKINGBYLENGTH": "Kicking by length",
    "CDLLADDERBOTTOM": "Ladder Bottom",
    "CDLLONGLEGGEDDOJI": "Long Legged Doji",
    "CDLLONGLINE": "Long Line Candle",
    "CDLMARUBOZU": "Marubozu",
    "CDLMATCHINGLOW": "Matching Low",
    "CDLMATHOLD": "Mat Hold",
    "CDLMORNINGDOJISTAR": ("Morning Doji Star", 3),
    "CDLMORNINGSTAR": ("Morning Star", 3),
    "CDLONNECK": "On-Neck Pattern",
    "CDLPIERCING": "Piercing Pattern",
    "CDLRICKSHAWMAN": "Rickshaw Man",
    "CDLRISEFALL3METHODS": ("Rising/Falling Three Methods", 3),
    "CDLSEPARATINGLINES": "Separating Lines",
    "CDLSHOOTINGSTAR": ("Shooting Star", 1),
    "CDLSHORTLINE": "Short Line Candle",
    "CDLSPINNINGTOP": "Spinning Top",
    "CDLSTALLEDPATTERN": "Stalled Pattern",
    "CDLSTICKSANDWICH": "Stick Sandwich",
    "CDLTAKURI": "Takuri",
    "CDLTASUKIGAP": "Tasuki Gap",
    "CDLTHRUSTING": ("Thrusting Pattern", 1),
    "CDLTRISTAR": "Tristar Pattern",
    "CDLUNIQUE3RIVER": "Unique 3 River",
    "CDLUPSIDEGAP2CROWS": ("Upside Gap Two Crows", 3),
    "CDLXSIDEGAP3METHODS": ("Upside/Downside Gap Three Methods", 2)
}
