# taken from https://thepatternsite.com
candle_pattern_names = {
    "CDL2CROWS_Bull": ("Two Crows", 61),
    "CDL2CROWS_Bear": ("Two Crows", 61),
    "CDL3BLACKCROWS_Bull": ("Three Black Crows", 3),
    "CDL3BLACKCROWS_Bear": ("Three Black Crows", 3),
    "CDL3INSIDE_Bull": ("Three Inside Up", 20),
    "CDL3INSIDE_Bear": ("Three Inside Down", 56),
    "CDL3LINESTRIKE_Bull": ("Three-Line Strike", 1),
    "CDL3LINESTRIKE_Bear": ("Three-Line Strike", 2),
    "CDL3OUTSIDE_Bull": ("Three Outside Up", 34),
    "CDL3OUTSIDE_Bear": ("Three Outside Down", 39),
    "CDL3STARSINSOUTH_Bull": ("Three Stars In The South", 103),
    "CDL3STARSINSOUTH_Bear": ("Three Stars In The South", 103),
    "CDL3WHITESOLDIERS_Bull": ("Three White Soldiers", 32),
    "CDL3WHITESOLDIERS_Bear": ("Three White Soldiers", 32),
    "CDLABANDONEDBABY_Bull": ("Abandoned Baby", 8),
    "CDLABANDONEDBABY_Bear": ("Abandoned Baby", 8),
    "CDLADVANCEBLOCK_Bull": ("Advance Block", 54),
    "CDLADVANCEBLOCK_Bear": ("Advance Block", 54),
    "CDLBELTHOLD_Bull": ("Belt-hold", 62),
    "CDLBELTHOLD_Bear": ("Belt-hold", 63),
    "CDLBREAKAWAY_Bull": ("Breakaway", 10),
    "CDLBREAKAWAY_Bear": ("Breakaway", 10),
    "CDLCLOSINGMARUBOZU_Bull": ("Closing Marubozu", 70),
    "CDLCLOSINGMARUBOZU_Bear": ("Closing Marubozu", 43),
    "CDLCONCEALBABYSWALL_Bull": ("Concealing Baby Swallow", 101),
    "CDLCONCEALBABYSWALL_Bear": ("Concealing Baby Swallow", 101),
    "CDLDARKCLOUDCOVER_Bull": ("Dark Cloud Cover", 22),
    "CDLDARKCLOUDCOVER_Bear": ("Dark Cloud Cover", 22),
    "CDLDOJI_Bull": ("Doji", 104),
    "CDLDOJI_Bear": ("Doji", 104),
    "CDLDOJISTAR_Bull": ("Doji Star", 49),
    "CDLDOJISTAR_Bear": ("Doji Star", 51),
    "CDLDRAGONFLYDOJI_Bull": ("Dragonfly Doji", 98),
    "CDLDRAGONFLYDOJI_Bear": ("Dragonfly Doji", 98),
    "CDLENGULFING_Bull": ("Engulfing Pattern", 84),
    "CDLENGULFING_Bear": ("Engulfing Pattern", 91),
    "CDLEVENINGDOJISTAR_Bull": ("Evening Doji Star", 30),
    "CDLEVENINGDOJISTAR_Bear": ("Evening Doji Star", 30),
    "CDLEVENINGSTAR_Bull": ("Evening Star", 4),
    "CDLEVENINGSTAR_Bear": ("Evening Star", 4),
    "CDLGAPSIDESIDEWHITE_Bull": ("Up-gap side-by-side white lines", 46),
    "CDLGAPSIDESIDEWHITE_Bear": ("Down-gap side-by-side white lines", 29),
    "CDLGRAVESTONEDOJI_Bull": ("Gravestone Doji", 77),
    "CDLGRAVESTONEDOJI_Bear": ("Gravestone Doji", 77),
    "CDLHAMMER_Bull": ("Hammer", 65),
    "CDLHAMMER_Bear": ("Hammer", 65),
    "CDLHANGINGMAN_Bull": ("Hanging Man", 87),
    "CDLHANGINGMAN_Bear": ("Hanging Man", 87),
    "CDLHARAMI_Bull": ("Harami Pattern", 38),
    "CDLHARAMI_Bear": ("Harami Pattern", 72),
    "CDLHARAMICROSS_Bull": ("Harami Cross Pattern", 50),
    "CDLHARAMICROSS_Bear": ("Harami Cross Pattern", 80),
    "CDLHIGHWAVE_Bull": ("High-Wave Candle", 67),
    "CDLHIGHWAVE_Bear": ("High-Wave Candle", 67),
    "CDLHIKKAKE_Bull": ("Hikkake Pattern", 85),
    "CDLHIKKAKE_Bear": ("Hikkake Pattern", 83),
    "CDLHIKKAKEMOD_Bull": ("Modified Hikkake Pattern", 82),
    "CDLHIKKAKEMOD_Bear": ("Modified Hikkake Pattern", 81),
    "CDLHOMINGPIGEON_Bull": ("Homing Pigeon", 21),
    "CDLHOMINGPIGEON_Bear": ("Homing Pigeon", 21),
    "CDLIDENTICAL3CROWS_Bull": ("Identical Three Crows", 24),
    "CDLIDENTICAL3CROWS_Bear": ("Identical Three Crows", 24),
    "CDLINNECK_Bull": ("In-Neck Pattern", 17),
    "CDLINNECK_Bear": ("In-Neck Pattern", 17),
    "CDLINVERTEDHAMMER_Bull": ("Inverted Hammer", 6),
    "CDLINVERTEDHAMMER_Bear": ("Inverted Hammer", 6),
    "CDLKICKING_Bull": ("Kicking", 96),
    "CDLKICKING_Bear": ("Kicking", 102),
    "CDLLADDERBOTTOM_Bull": ("Ladder Bottom", 41),
    "CDLLADDERBOTTOM_Bear": ("Ladder Bottom", 41),
    "CDLLONGLEGGEDDOJI_Bull": ("Long Legged Doji", 37),
    "CDLLONGLEGGEDDOJI_Bear": ("Long Legged Doji", 37),
    "CDLMARUBOZU_Bull": ("Marubozu", 71),
    "CDLMARUBOZU_Bear": ("Marubozu", 57),
    "CDLMATCHINGLOW_Bull": ("Matching Low", 7),
    "CDLMATCHINGLOW_Bear": ("Matching Low", 7),
    "CDLMATHOLD_Bull": ("Mat Hold", 86),
    "CDLMATHOLD_Bear": ("Mat Hold", 86),
    "CDLMORNINGDOJISTAR_Bull": ("Morning Doji Star", 25),
    "CDLMORNINGDOJISTAR_Bear": ("Morning Doji Star", 25),
    "CDLMORNINGSTAR_Bull": ("Morning Star", 12),
    "CDLMORNINGSTAR_Bear": ("Morning Star", 12),
    "CDLONNECK_Bull": ("On-Neck Pattern", 33),
    "CDLONNECK_Bear": ("On-Neck Pattern", 33),
    "CDLPIERCING_Bull": ("Piercing Pattern", 13),
    "CDLPIERCING_Bear": ("Piercing Pattern", 13),
    "CDLRICKSHAWMAN_Bull": ("Rickshaw Man", 35),
    "CDLRICKSHAWMAN_Bear": ("Rickshaw Man", 35),
    "CDLRISEFALL3METHODS_Bull": ("Rising Three Methods", 94),
    "CDLRISEFALL3METHODS_Bear": ("Falling Three Methods", 89),
    "CDLSEPARATINGLINES_Bull": ("Separating Lines", 36),
    "CDLSEPARATINGLINES_Bear": ("Separating Lines", 40),
    "CDLSHOOTINGSTAR_Bull": ("Shooting Star", 55),
    "CDLSHOOTINGSTAR_Bear": ("Shooting Star", 55),
    "CDLSPINNINGTOP_Bull": ("Spinning Top", 69),
    "CDLSPINNINGTOP_Bear": ("Spinning Top", 73),
    "CDLSTICKSANDWICH_Bull": ("Stick Sandwich", 14),
    "CDLSTICKSANDWICH_Bear": ("Stick Sandwich", 14),
    "CDLTAKURI_Bull": ("Takuri", 47),
    "CDLTAKURI_Bear": ("Takuri", 47),
    "CDLTASUKIGAP_Bull": ("Tasuki Gap", 5),
    "CDLTASUKIGAP_Bear": ("Tasuki Gap", 5),
    "CDLTHRUSTING_Bull": ("Thrusting Pattern", 15),
    "CDLTHRUSTING_Bear": ("Thrusting Pattern", 15),
    "CDLTRISTAR_Bull": ("Tristar Pattern", 28),
    "CDLTRISTAR_Bear": ("Tristar Pattern", 76),
    "CDLUNIQUE3RIVER_Bull": ("Unique 3 River", 60),
    "CDLUNIQUE3RIVER_Bear": ("Unique 3 River", 60),
    "CDLUPSIDEGAP2CROWS_Bull": ("Upside Gap Two Crows", 74),
    "CDLUPSIDEGAP2CROWS_Bear": ("Upside Gap Two Crows", 74),
    "CDLXSIDEGAP3METHODS_Bull": ("Upside Gap Three Methods", 27),
    "CDLXSIDEGAP3METHODS_Bear": ("Downside Gap Three Methods", 26),
}
